import { ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { createHash } from 'crypto';
import Decimal from 'decimal.js';
import { Prisma, PayrollStatus, Role } from '@prisma/client';
import { PrismaService } from '../prisma.service';
import { ActorDto, AdjustmentDto, CreateRunDto, PolicyDto } from './payroll.dto';
import { calculateEmployee, PayrollEmployeeInput, PayrollRules } from './engine';
import { renderPayslip } from './payslip';
@Injectable() export class PayrollService {
  constructor(private readonly db:PrismaService){}
  listPolicies(organizationId:string){return this.db.payrollPolicy.findMany({where:{organizationId},orderBy:[{name:'asc'},{version:'desc'}]});}
  async createPolicy(dto:PolicyDto){const actor=await this.actor(dto.actorId,dto.organizationId,['PAYROLL','ADMIN']);this.validateRules(dto.rules);const latest=await this.db.payrollPolicy.aggregate({where:{organizationId:dto.organizationId,name:dto.name},_max:{version:true}});const policy=await this.db.payrollPolicy.create({data:{organizationId:dto.organizationId,name:dto.name,version:(latest._max.version??0)+1,effectiveFrom:new Date(dto.effectiveFrom),currency:dto.currency,rules:dto.rules as Prisma.InputJsonValue,createdById:actor.id}});await this.audit(dto.organizationId,actor.id,'PAYROLL_POLICY_CREATED','PayrollPolicy',policy.id,{version:policy.version});return policy;}
  async approvePolicy(id:string,actorId:string){const policy=await this.db.payrollPolicy.findUnique({where:{id}});if(!policy)throw new NotFoundException('Policy not found');const actor=await this.actor(actorId,policy.organizationId,['FINANCE','ADMIN']);if(policy.createdById===actor.id)throw new ForbiddenException('Policy creator cannot approve the same version');if(policy.status!=='DRAFT')throw new ConflictException('Only draft policies can be approved');const updated=await this.db.payrollPolicy.update({where:{id},data:{status:'APPROVED',approvedById:actor.id,approvedAt:new Date()}});await this.audit(policy.organizationId,actor.id,'PAYROLL_POLICY_APPROVED','PayrollPolicy',id,{version:policy.version});return updated;}
  async createRun(dto:CreateRunDto){const actor=await this.actor(dto.actorId,dto.organizationId,['PAYROLL','ADMIN']);const start=new Date(dto.periodStart),end=new Date(dto.periodEnd);if(end<=start)throw new ConflictException('periodEnd must be after periodStart');const policy=await this.db.payrollPolicy.findUnique({where:{id:dto.policyId}});if(!policy||policy.organizationId!==dto.organizationId||policy.status!=='APPROVED')throw new ConflictException('An approved organization policy is required');const profiles=await this.db.compensationProfile.findMany({where:{employee:{organizationId:dto.organizationId,active:true},effectiveFrom:{lte:end},OR:[{effectiveTo:null},{effectiveTo:{gte:start}}]},include:{employee:true},orderBy:{effectiveFrom:'desc'}});const unique=[...new Map(profiles.map(p=>[p.employeeId,p])).values()];const employees=[];for(const profile of unique){const [summaries,overtime]=await Promise.all([this.db.dailyAttendanceSummary.findMany({where:{employeeId:profile.employeeId,localDate:{gte:start,lte:end}}}),this.db.request.findMany({where:{employeeId:profile.employeeId,type:'OVERTIME',status:'APPROVED',startsAt:{lte:end},endsAt:{gte:start}}})]);employees.push({employeeId:profile.employeeId,employeeNumber:profile.employee.employeeNumber,name:profile.employee.name,monthlyBase:profile.monthlyBase.toString(),hourlyRate:profile.hourlyRate?.toString()??null,workedMinutes:summaries.reduce((n,s)=>n+s.workedMinutes,0),scheduledMinutes:summaries.length*((policy.rules as any).regularMinutesPerDay??480),overtimeMinutes:overtime.reduce((n,r)=>n+Math.max(0,Math.round((r.endsAt.getTime()-r.startsAt.getTime())/60000)),0),lateMinutes:summaries.reduce((n,s)=>n+s.lateMinutes,0),undertimeMinutes:summaries.reduce((n,s)=>n+s.undertimeMinutes,0),allowances:profile.allowances,deductions:profile.deductions});}const snapshot={createdAt:new Date().toISOString(),periodStart:start.toISOString(),periodEnd:end.toISOString(),policy:{id:policy.id,version:policy.version,rules:policy.rules,currency:policy.currency},employees};const run=await this.db.payrollRun.create({data:{organizationId:dto.organizationId,periodStart:start,periodEnd:end,policyVersion:policy.version,policyId:policy.id,inputSnapshot:snapshot as Prisma.InputJsonValue,createdById:actor.id}});await this.history(run.id,actor.id,'CREATED','DRAFT','DRAFT',run.revision);return run;}
  listRuns(organizationId:string){return this.db.payrollRun.findMany({where:{organizationId},include:{_count:{select:{items:true,adjustments:true}}},orderBy:{createdAt:'desc'}});}
  async calculate(id:string,actorId:string){const run=await this.db.payrollRun.findUnique({where:{id},include:{adjustments:true,policy:true}});if(!run)throw new NotFoundException('Payroll run not found');const actor=await this.actor(actorId,run.organizationId,['PAYROLL','ADMIN']);if(!['DRAFT','CALCULATED'].includes(run.status))throw new ConflictException('Approved or locked payroll cannot be recalculated');const snapshot=run.inputSnapshot as any;const results=(snapshot.employees as PayrollEmployeeInput[]).map(employee=>calculateEmployee(employee,snapshot.policy.rules as PayrollRules));const adjustmentByEmployee=new Map<string,typeof run.adjustments>();for(const adjustment of run.adjustments){const items=adjustmentByEmployee.get(adjustment.employeeId)??[];items.push(adjustment);adjustmentByEmployee.set(adjustment.employeeId,items);}const data:any[]=[];for(const result of results){for(const line of result.lines)data.push({payrollRunId:id,employeeId:result.employeeId,code:line.code,description:line.description,category:line.category,amount:line.amount,taxable:line.taxable,explanation:line.explanation});for(const adjustment of adjustmentByEmployee.get(result.employeeId)??[])data.push({payrollRunId:id,employeeId:result.employeeId,code:adjustment.code,description:adjustment.description,category:new Decimal(adjustment.amount.toString()).gte(0)?'EARNING':'DEDUCTION',amount:new Decimal(adjustment.amount.toString()).abs().toFixed(2),taxable:false,explanation:{source:'MANUAL_ADJUSTMENT',reason:adjustment.reason,createdById:adjustment.createdById}});}const hash=createHash('sha256').update(JSON.stringify({snapshot,data})).digest('hex');await this.db.$transaction([this.db.payrollLineItem.deleteMany({where:{payrollRunId:id}}),this.db.payrollLineItem.createMany({data}),this.db.payrollRun.update({where:{id},data:{status:'CALCULATED',calculationHash:hash}})]);await this.history(id,actor.id,'CALCULATED',run.status,'CALCULATED',run.revision);return this.db.payrollRun.findUnique({where:{id},include:{items:true}});}
  async adjust(id:string,dto:AdjustmentDto){const run=await this.db.payrollRun.findUnique({where:{id}});if(!run)throw new NotFoundException();const actor=await this.actor(dto.actorId,run.organizationId,['PAYROLL','ADMIN']);if(!['DRAFT','CALCULATED'].includes(run.status))throw new ConflictException('Locked or approved payroll cannot be adjusted');const employee=await this.db.employee.findUnique({where:{id:dto.employeeId}});if(!employee||employee.organizationId!==run.organizationId)throw new ConflictException('Employee is outside this payroll');const adjustment=await this.db.payrollAdjustment.create({data:{payrollRunId:id,employeeId:dto.employeeId,createdById:actor.id,code:dto.code,description:dto.description,amount:dto.amount,reason:dto.reason}});await this.audit(run.organizationId,actor.id,'PAYROLL_ADJUSTMENT_CREATED','PayrollAdjustment',adjustment.id,{payrollRunId:id,amount:dto.amount});return adjustment;}
  async transition(id:string,actorId:string,target:'APPROVED'|'LOCKED',reason?:string){const run=await this.db.payrollRun.findUnique({where:{id}});if(!run)throw new NotFoundException();const roles=target==='APPROVED'?['FINANCE','ADMIN']:['FINANCE','ADMIN'];const actor=await this.actor(actorId,run.organizationId,roles);const expected=target==='APPROVED'?'CALCULATED':'APPROVED';if(run.status!==expected)throw new ConflictException(`${target} requires ${expected} status`);if(target==='APPROVED'&&run.createdById===actor.id)throw new ForbiddenException('Payroll preparer cannot approve the same run');const updated=await this.db.payrollRun.update({where:{id},data:{status:target,approvedById:target==='APPROVED'?actor.id:run.approvedById,approvedAt:target==='APPROVED'?new Date():run.approvedAt,lockedAt:target==='LOCKED'?new Date():run.lockedAt}});await this.history(id,actor.id,target,run.status,target,run.revision,reason);return updated;}
  async reopen(id:string,actorId:string,reason?:string){if(!reason||reason.trim().length<5)throw new ConflictException('A reopening reason is required');const run=await this.db.payrollRun.findUnique({where:{id}});if(!run||run.status!=='LOCKED')throw new ConflictException('Only locked payroll can be reopened');const actor=await this.actor(actorId,run.organizationId,['ADMIN']);const updated=await this.db.payrollRun.update({where:{id},data:{status:'DRAFT',revision:{increment:1},reopenedAt:new Date(),reopenReason:reason,lockedAt:null,approvedAt:null,approvedById:null}});await this.history(id,actor.id,'REOPENED','LOCKED','DRAFT',updated.revision,reason);return updated;}
  async payslip(id:string,employeeId:string,actorId:string){const run=await this.db.payrollRun.findUnique({where:{id},include:{organization:true,policy:true,items:{where:{employeeId}},payslips:{where:{employeeId}}}});if(!run||run.status!=='LOCKED')throw new ConflictException('Payslips require locked payroll');const actor=await this.db.employee.findUnique({where:{id:actorId}});if(!actor||actor.organizationId!==run.organizationId||(actor.id!==employeeId&&!['PAYROLL','FINANCE','ADMIN'].includes(actor.role)))throw new ForbiddenException();const employee=await this.db.employee.findUnique({where:{id:employeeId}});if(!employee)throw new NotFoundException();const earnings=run.items.filter(i=>i.category==='EARNING').reduce((n,i)=>n.plus(i.amount.toString()),new Decimal(0));const deductions=run.items.filter(i=>i.category==='DEDUCTION').reduce((n,i)=>n.plus(i.amount.toString()),new Decimal(0));return renderPayslip({company:run.organization.name,employee:employee.name,employeeNumber:employee.employeeNumber,period:`${run.periodStart.toISOString().slice(0,10)} to ${run.periodEnd.toISOString().slice(0,10)}`,currency:run.policy?.currency??'PHP',lines:run.items.map(i=>({description:i.description,category:i.category,amount:i.amount.toFixed(2)})),gross:earnings.toFixed(2),deductions:deductions.toFixed(2),net:earnings.minus(deductions).toFixed(2)});}
  private validateRules(rules:Record<string,unknown>){for(const key of ['basePayDivisor','regularMinutesPerDay','overtimeMultiplier'])if(rules[key]===undefined)throw new ConflictException(`Policy rule ${key} is required`);if(new Decimal(String(rules.basePayDivisor)).lte(0)||Number(rules.regularMinutesPerDay)<=0||new Decimal(String(rules.overtimeMultiplier)).lt(0))throw new ConflictException('Payroll policy contains invalid numeric rules');}
  private async actor(id:string,organizationId:string,roles:string[]){const actor=await this.db.employee.findUnique({where:{id}});if(!actor||actor.organizationId!==organizationId||!roles.includes(actor.role))throw new ForbiddenException(`Requires role: ${roles.join(' or ')}`);return actor;}
  private history(payrollRunId:string,actorId:string,action:string,fromStatus:PayrollStatus,toStatus:PayrollStatus,revision:number,reason?:string){return this.db.payrollRunHistory.create({data:{payrollRunId,actorId,action,fromStatus,toStatus,revision,reason}});}
  private audit(organizationId:string,actorId:string,action:string,entityType:string,entityId:string,metadata:Record<string,unknown>){return this.db.auditLog.create({data:{organizationId,actorId,action,entityType,entityId,metadata:metadata as Prisma.InputJsonValue}});}
}
