'use client';
import { Check, X } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { apiRequest, appConfig, formatDate } from '../lib/api';
import { ErrorPanel, LoadingPanel, SuccessMessage } from './feedback';
type RequestRow={id:string;type:string;startsAt:string;endsAt:string;reason:string;status:string;currentStep:number;employee:{name:string;employeeNumber:string};steps:{sequence:number;approverRole:string}[]};
export function ApprovalsView(){const [rows,setRows]=useState<RequestRow[]>([]);const [status,setStatus]=useState('PENDING');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [success,setSuccess]=useState('');
const load=useCallback(async()=>{setLoading(true);setError('');try{setRows(await apiRequest<RequestRow[]>(`/requests?organizationId=${appConfig.organizationId}&status=${status}`));}catch(e){setError(e instanceof Error?e.message:'Unknown error');}finally{setLoading(false);}},[status]);useEffect(()=>{void load();},[load]);
const pending=useMemo(()=>rows.filter(row=>row.status==='PENDING'),[rows]);
async function decide(row:RequestRow,decision:'APPROVED'|'REJECTED'){const label=decision==='APPROVED'?'approve':'reject';if(!window.confirm(`Are you sure you want to ${label} ${row.employee.name}'s request?`))return;const role=row.steps.find(step=>step.sequence===row.currentStep)?.approverRole;const actorId=role==='SUPERVISOR'?appConfig.supervisorActorId:appConfig.hrActorId;setBusy(row.id);setError('');setSuccess('');try{await apiRequest(`/requests/${row.id}/decision`,{method:'POST',body:JSON.stringify({actorId,decision,comment:`Decision recorded in HERRERA ATTEND back office`})});setSuccess(`${row.employee.name}'s request was ${decision.toLowerCase()}.`);await load();}catch(e){setError(e instanceof Error?e.message:'Decision failed');}finally{setBusy('');}}
return <><header className="pageHeader"><div><span className="eyebrow">Maker-checker · Live workflow</span><h1>Approval queue</h1><p>Review and decide employee requests with a complete audit trail.</p></div></header><div className="tabs" role="tablist"><button className={status==='PENDING'?'tab active':'tab'} onClick={()=>setStatus('PENDING')}>Pending</button><button className={status==='APPROVED'?'tab active':'tab'} onClick={()=>setStatus('APPROVED')}>Approved</button><button className={status==='REJECTED'?'tab active':'tab'} onClick={()=>setStatus('REJECTED')}>Rejected</button></div>{success&&<SuccessMessage message={success}/>}<section className="panel">{loading?<LoadingPanel label="Loading requests…"/>:error?<ErrorPanel message={error} retry={()=>void load()}/>:<div className="tableWrap" tabIndex={0} role="region" aria-label="Approval requests"><table><caption className="srOnly">Employee approval requests</caption><thead><tr><th scope="col">Employee</th><th scope="col">Type</th><th scope="col">Period</th><th scope="col">Reason</th><th scope="col">Step</th><th scope="col">Actions</th></tr></thead><tbody>{rows.length?rows.map(row=><tr key={row.id}><td><strong>{row.employee.name}</strong><br/><small>{row.employee.employeeNumber}</small></td><td>{row.type.replaceAll('_',' ')}</td><td>{formatDate(row.startsAt)}<br/>to {formatDate(row.endsAt)}</td><td className="wrapCell">{row.reason}</td><td><span className="pill review">{row.steps.find(step=>step.sequence===row.currentStep)?.approverRole??row.status}</span></td><td>{row.status==='PENDING'?<div className="rowActions"><button disabled={busy===row.id} type="button" className="small" onClick={()=>void decide(row,'APPROVED')}><Check size={13}/>Approve</button><button disabled={busy===row.id} type="button" className="small dangerButton" onClick={()=>void decide(row,'REJECTED')}><X size={13}/>Reject</button></div>:<span className={row.status==='APPROVED'?'pill':'pill review'}>{row.status}</span>}</td></tr>):<tr><td colSpan={6}><div className="emptyTable">No {status.toLowerCase()} requests.</div></td></tr>}</tbody></table></div>}</section></>}
