'use client';
import { Download, Search } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { apiRequest, appConfig, formatDate } from '../lib/api';
import { ErrorPanel, LoadingPanel } from './feedback';

type Summary={id:string;firstClockIn:string|null;lastClockOut:string|null;workedMinutes:number;employee:{id:string;name:string;employeeNumber:string;worksite:{name:string}|null}};

export function AttendanceView(){
  const [date,setDate]=useState('2026-07-20');const [query,setQuery]=useState('');const [rows,setRows]=useState<Summary[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{setRows(await apiRequest<Summary[]>(`/attendance/summaries?organizationId=${appConfig.organizationId}&date=${date}`));}catch(e){setError(e instanceof Error?e.message:'Unknown error');}finally{setLoading(false);}},[date]);
  useEffect(()=>{void load();},[load]);
  const visible=useMemo(()=>rows.filter(row=>row.employee.name.toLowerCase().includes(query.toLowerCase())||row.employee.employeeNumber.toLowerCase().includes(query.toLowerCase())),[rows,query]);
  const exportUrl=`${appConfig.apiUrl}/reports/DAILY_ATTENDANCE?organizationId=${appConfig.organizationId}&actorId=${appConfig.hrActorId}&format=CSV&from=${date}&to=${date}`;
  return <><header className="pageHeader"><div><span className="eyebrow">Workforce · Live API data</span><h1>Daily attendance</h1><p>Review server-calculated employee timecards.</p></div><a className="buttonLink" href={exportUrl}><Download size={15}/>Export CSV</a></header><section className="panel"><div className="filters"><label className="searchField"><Search size={15}/><span className="srOnly">Search employees</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search employees"/></label><label className="fieldLabel"><span>Date</span><input type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><button type="button" className="secondary" onClick={()=>void load()}>Refresh</button></div>{loading?<LoadingPanel label="Loading attendance…"/>:error?<ErrorPanel message={error} retry={()=>void load()}/>:<div className="tableWrap" tabIndex={0} role="region" aria-label="Daily attendance"><table><caption className="srOnly">Daily employee attendance records</caption><thead><tr><th scope="col">Employee</th><th scope="col">Worksite</th><th scope="col">First in</th><th scope="col">Last out</th><th scope="col">Worked</th><th scope="col">Status</th></tr></thead><tbody>{visible.length?visible.map(row=><tr key={row.id}><td><span className="employeeCell"><span className="miniAvatar">{row.employee.name.split(' ').map(n=>n[0]).join('')}</span><span><strong>{row.employee.name}</strong><small>{row.employee.employeeNumber}</small></span></span></td><td>{row.employee.worksite?.name??'Unassigned'}</td><td>{row.firstClockIn?formatDate(row.firstClockIn):'—'}</td><td>{row.lastClockOut?formatDate(row.lastClockOut):'—'}</td><td>{Math.floor(row.workedMinutes/60)}h {row.workedMinutes%60}m</td><td><span className={row.firstClockIn&&row.lastClockOut?'pill':'pill review'}>{row.firstClockIn&&row.lastClockOut?'Complete':'Needs review'}</span></td></tr>):<tr><td colSpan={6}><div className="emptyTable">No attendance summaries match this date and search.</div></td></tr>}</tbody></table></div>}</section></>;
}
