'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { CheckCheck, FileSliders, Plus, RefreshCw } from 'lucide-react';
import { apiRequest, appConfig } from '../lib/api';
import { ErrorPanel, LoadingPanel, SuccessMessage } from './feedback';

type Policy={id:string;name:string;version:number;status:'DRAFT'|'APPROVED'|'RETIRED';effectiveFrom:string;currency:string;rules:{basePayDivisor?:number;regularMinutesPerDay?:number;overtimeMultiplier?:string|number}};
const fieldsStyle={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12} as const;

export function PayrollPoliciesView(){
 const [policies,setPolicies]=useState<Policy[]>([]),[name,setName]=useState('Standard payroll policy'),[effectiveFrom,setEffectiveFrom]=useState(new Date().toISOString().slice(0,10)),[divisor,setDivisor]=useState('2'),[minutes,setMinutes]=useState('480'),[overtime,setOvertime]=useState('1.25'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{setPolicies(await apiRequest<Policy[]>(`/payroll/policies?organizationId=${appConfig.organizationId}`));}catch(e){setError(e instanceof Error?e.message:'Unable to load payroll policies');}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);
 async function submit(event:FormEvent){event.preventDefault();setError('');setSuccess('');const d=Number(divisor),m=Number(minutes),o=Number(overtime);if(name.trim().length<3)return setError('Policy name must contain at least 3 characters.');if(d<=0||!Number.isFinite(d))return setError('Pay divisor must be greater than zero.');if(!Number.isInteger(m)||m<1||m>1440)return setError('Regular minutes must be a whole number from 1 to 1,440.');if(o<0||!Number.isFinite(o))return setError('Overtime multiplier cannot be negative.');setBusy('create');try{await apiRequest('/payroll/policies',{method:'POST',body:JSON.stringify({organizationId:appConfig.organizationId,name:name.trim(),effectiveFrom,currency:'PHP',actorId:appConfig.payrollActorId,rules:{classification:'COMPANY_POLICY',basePayDivisor:d,regularMinutesPerDay:m,overtimeMultiplier:o.toFixed(2),rounding:'HALF_UP',deductions:[]}})});setSuccess('Draft payroll policy created. A finance approver must approve it.');await load();}catch(e){setError(e instanceof Error?e.message:'Unable to create policy');}finally{setBusy('');}}
 async function approve(policy:Policy){if(!window.confirm(`Approve ${policy.name} version ${policy.version}?`))return;setBusy(policy.id);setError('');setSuccess('');try{await apiRequest(`/payroll/policies/${policy.id}/approve`,{method:'POST',body:JSON.stringify({actorId:appConfig.financeActorId})});setSuccess(`${policy.name} v${policy.version} approved.`);await load();}catch(e){setError(e instanceof Error?e.message:'Unable to approve policy');}finally{setBusy('');}}
 return <><header className="pageHeader"><div><span className="eyebrow">Payroll governance · Maker-checker</span><h1>Payroll policies</h1><p>Define calculation rules, then send each version to an independent finance approver.</p></div><button className="secondary" onClick={()=>void load()}><RefreshCw size={14}/>Refresh</button></header>{success&&<SuccessMessage message={success}/>} {error&&!loading&&<div className="successMessage errorMessage" role="alert">{error}</div>}<form className="panel" style={{display:'grid',gap:14}} onSubmit={submit}><div className="panelHead"><div><h2>Create policy version</h2><p>Currency is fixed to Philippine peso for this organization.</p></div><FileSliders size={22}/></div><div style={fieldsStyle}><label className="fieldLabel">Policy name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label className="fieldLabel">Effective from<input required type="date" value={effectiveFrom} onChange={e=>setEffectiveFrom(e.target.value)}/></label><label className="fieldLabel">Semi-monthly divisor<input required min="0.01" step="0.01" type="number" value={divisor} onChange={e=>setDivisor(e.target.value)}/></label><label className="fieldLabel">Regular minutes / day<input required min="1" max="1440" step="1" type="number" value={minutes} onChange={e=>setMinutes(e.target.value)}/></label><label className="fieldLabel">Overtime multiplier<input required min="0" step="0.01" type="number" value={overtime} onChange={e=>setOvertime(e.target.value)}/></label></div><button disabled={busy==='create'} type="submit"><Plus size={14}/>{busy==='create'?'Creating…':'Create draft policy'}</button></form><section className="panel payrollTable"><div className="panelHead"><div><h2>Policy versions</h2><p>Approved versions can be selected when creating a payroll run.</p></div></div>{loading?<LoadingPanel label="Loading payroll policies…"/>:error?<ErrorPanel message={error} retry={()=>void load()}/>:<div className="tableWrap"><table><thead><tr><th>Name</th><th>Version</th><th>Effective</th><th>Regular day</th><th>OT multiplier</th><th>Status</th><th>Action</th></tr></thead><tbody>{policies.length?policies.map(p=><tr key={p.id}><td><strong>{p.name}</strong></td><td>v{p.version}</td><td>{new Date(p.effectiveFrom).toLocaleDateString('en-PH')}</td><td>{p.rules.regularMinutesPerDay??'—'} min</td><td>{p.rules.overtimeMultiplier??'—'}×</td><td><span className={p.status==='APPROVED'?'pill':'pill review'}>{p.status}</span></td><td>{p.status==='DRAFT'?<button className="small" disabled={busy===p.id} onClick={()=>void approve(p)} type="button"><CheckCheck size={13}/>{busy===p.id?'Approving…':'Approve'}</button>:<span className="mutedText">Ready for payroll</span>}</td></tr>):<tr><td colSpan={7}><div className="emptyTable">No payroll policies yet.</div></td></tr>}</tbody></table></div>}</section></>;
}
