'use client';
import { ArrowDownToLine, FileChartColumn } from 'lucide-react';
import { useEffect, useState } from 'react';
import { apiRequest, appConfig } from '../lib/api';
import { SuccessMessage } from './feedback';
const reports=[['DAILY_ATTENDANCE','Daily attendance','Attendance','Clock events, worked time, late and undertime'],['TIMECARD','Employee timecards','Attendance','Per-employee period detail'],['EXCEPTIONS','Attendance exceptions','Compliance','Open and resolved exception evidence'],['OVERTIME','Overtime requests','Approvals','Requested, approved and rejected overtime'],['PAYROLL_REGISTER','Payroll register','Payroll','Every employee payroll line item'],['PAYROLL_SUMMARY','Payroll summary','Payroll','Gross, deductions and net totals'],['PAYROLL_VARIANCE','Payroll variance','Payroll','Current period against previous period'],['DEDUCTIONS','Deduction register','Payroll','Policy, profile and manual deductions'],['AUDIT_LOG','Audit log','Security','Privileged and state-changing actions']] as const;
type Run={id:string;periodStart:string;periodEnd:string;status:string};
export function ReportsView(){const [format,setFormat]=useState('CSV');const [from,setFrom]=useState('2026-07-01');const [to,setTo]=useState('2026-07-31');const [runId,setRunId]=useState('');const [runs,setRuns]=useState<Run[]>([]);const [busy,setBusy]=useState('');const [message,setMessage]=useState('');const [error,setError]=useState('');useEffect(()=>{apiRequest<Run[]>(`/payroll/runs?organizationId=${appConfig.organizationId}`).then(data=>{setRuns(data);setRunId(data[0]?.id??'');}).catch(e=>setError(e instanceof Error?e.message:'Unable to load payroll runs'));},[]);async function generate(type:string,name:string){setBusy(type);setError('');setMessage('');try{const payroll=type.startsWith('PAYROLL')||type==='DEDUCTIONS';if(payroll&&!runId)throw new Error('Select a payroll run first.');const params=new URLSearchParams({organizationId:appConfig.organizationId,actorId:type==='AUDIT_LOG'?appConfig.hrActorId:payroll?appConfig.payrollActorId:appConfig.hrActorId,format,from,to});if(payroll)params.set('runId',runId);const response=await fetch(`${appConfig.apiUrl}/reports/${type}?${params}`);if(!response.ok){const body=await response.json().catch(()=>null) as {message?:string}|null;throw new Error(body?.message||'Report generation failed');}const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`${type.toLowerCase()}-${to}.${format.toLowerCase()}`;anchor.click();URL.revokeObjectURL(url);setMessage(`${name} downloaded successfully.`);}catch(e){setError(e instanceof Error?e.message:'Report generation failed');}finally{setBusy('');}}
return <><header className="pageHeader"><div><span className="eyebrow">Authoritative exports · Live API</span><h1>Reports library</h1><p>Configure and download auditable CSV or PDF reports.</p></div></header><section className="panel reportConfig"><div className="filters"><label className="fieldLabel"><span>From</span><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="fieldLabel"><span>To</span><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label className="fieldLabel"><span>Format</span><select value={format} onChange={e=>setFormat(e.target.value)}><option>CSV</option><option>PDF</option></select></label><label className="fieldLabel growField"><span>Payroll run</span><select value={runId} onChange={e=>setRunId(e.target.value)}><option value="">Select run</option>{runs.map(run=><option key={run.id} value={run.id}>{new Date(run.periodStart).toLocaleDateString()} – {new Date(run.periodEnd).toLocaleDateString()} ({run.status})</option>)}</select></label></div></section>{message&&<SuccessMessage message={message}/>} {error&&<div className="successMessage errorMessage" role="alert">{error}</div>}<section className="reportGrid">{reports.map(([type,name,group,description])=>{const unavailable=type==='AUDIT_LOG';return <article className="panel reportCard" key={type}><span className="reportIcon"><FileChartColumn size={19}/></span><span className="eyebrow">{group}</span><h2>{name}</h2><p>{description}</p><div><small>{unavailable?'Auditor role required':`${format} export`}</small><button disabled={busy===type||unavailable} onClick={()=>void generate(type,name)} className="small"><ArrowDownToLine size={13}/>{busy===type?'Generating…':unavailable?'Restricted':'Generate'}</button></div></article>})}</section></>}
