'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { MapPin, Plus, RefreshCw } from 'lucide-react';
import { apiRequest, appConfig } from '../lib/api';
import { ErrorPanel, LoadingPanel } from './feedback';

type Worksite = { id:string; name:string; latitude:number|string; longitude:number|string; radiusMeters:number; maxAccuracyMeters:number };
const emptyForm = { name:'', latitude:'', longitude:'', radiusMeters:'100', maxAccuracyMeters:'50' };

export function WorkforceWorksitesView() {
  const [rows,setRows]=useState<Worksite[]>([]); const [form,setForm]=useState(emptyForm);
  const [showForm,setShowForm]=useState(false); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
  const [error,setError]=useState(''); const [message,setMessage]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{setRows(await apiRequest<Worksite[]>(`/workforce/worksites?organizationId=${appConfig.organizationId}`));}catch(cause){setError(cause instanceof Error?cause.message:'Unable to load worksites.');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError('');setMessage('');try{await apiRequest('/workforce/worksites',{method:'POST',body:JSON.stringify({organizationId:appConfig.organizationId,name:form.name.trim(),latitude:Number(form.latitude),longitude:Number(form.longitude),radiusMeters:Number(form.radiusMeters),maxAccuracyMeters:Number(form.maxAccuracyMeters)})});setForm(emptyForm);setShowForm(false);setMessage('Worksite added successfully.');await load();}catch(cause){setError(cause instanceof Error?cause.message:'Unable to add worksite.');}finally{setSaving(false);}}
  return <><header className="pageHeader"><div><span className="eyebrow">Workforce · Location management</span><h1>Worksites</h1><p>Define approved clock-in areas and GPS accuracy requirements for each workplace.</p></div><div className="actions"><button type="button" className="secondary" onClick={()=>void load()}><RefreshCw size={14}/>Refresh</button><button type="button" onClick={()=>setShowForm(value=>!value)}><Plus size={15}/>{showForm?'Close form':'Add worksite'}</button></div></header>
  {message&&<div className="successMessage" role="status">{message}</div>}{error&&rows.length>0&&<div className="successMessage errorMessage" role="alert">{error}</div>}
  {showForm&&<section className="panel" aria-labelledby="worksite-form-title"><div className="panelHead"><div><h2 id="worksite-form-title">New worksite</h2><p>Coordinates use decimal degrees. The radius defines the allowed clock-in boundary.</p></div></div><form onSubmit={submit}><div className="filters"><label className="fieldLabel growField"><span>Worksite name</span><input required maxLength={120} value={form.name} onChange={event=>setForm({...form,name:event.target.value})} placeholder="Herrera Main Office"/></label><label className="fieldLabel"><span>Latitude</span><input required type="number" step="any" min="-90" max="90" value={form.latitude} onChange={event=>setForm({...form,latitude:event.target.value})} placeholder="14.5995"/></label><label className="fieldLabel"><span>Longitude</span><input required type="number" step="any" min="-180" max="180" value={form.longitude} onChange={event=>setForm({...form,longitude:event.target.value})} placeholder="120.9842"/></label><label className="fieldLabel"><span>Geofence radius (m)</span><input required type="number" min="1" max="5000" value={form.radiusMeters} onChange={event=>setForm({...form,radiusMeters:event.target.value})}/></label><label className="fieldLabel"><span>Max GPS error (m)</span><input required type="number" min="1" max="1000" value={form.maxAccuracyMeters} onChange={event=>setForm({...form,maxAccuracyMeters:event.target.value})}/></label><button disabled={saving} type="submit">{saving?'Saving…':'Save worksite'}</button></div></form></section>}
  <section className="panel"><div className="panelHead"><div><h2>Registered worksites</h2><p>{rows.length} approved location{rows.length===1?'':'s'}</p></div></div>{loading?<LoadingPanel label="Loading worksites…"/>:error&&!rows.length?<ErrorPanel message={error} retry={()=>void load()}/>:<div className="tableWrap" tabIndex={0} role="region" aria-label="Registered worksites"><table><thead><tr><th scope="col">Worksite</th><th scope="col">Coordinates</th><th scope="col">Clock-in radius</th><th scope="col">GPS accuracy limit</th><th scope="col">Status</th></tr></thead><tbody>{rows.length?rows.map(site=><tr key={site.id}><td><span className="employeeCell"><span className="miniAvatar"><MapPin size={13}/></span><strong>{site.name}</strong></span></td><td>{Number(site.latitude).toFixed(6)}, {Number(site.longitude).toFixed(6)}</td><td>{site.radiusMeters} m</td><td>{site.maxAccuracyMeters} m</td><td><span className="pill">Active</span></td></tr>):<tr><td colSpan={5}><div className="emptyTable">No worksites yet. Add your first approved location above.</div></td></tr>}</tbody></table></div>}</section></>;
}
